version: '3.7'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - PLEX_CLAIM=${PLEX_CLAIM}
    network_mode: host
    volumes:
      - plex-config:/config
      - plex-transcode:/transcode
      - ${PLEX_DATA}:/data

volumes:
  plex-config:
  plex-transcode:
