env:
  TERM: xterm-256color 
window:
  padding:
    x: 5
    y: 5

colors:
  primary:
    background: "0x2d2a2e"
    foreground: "0xe3e1e4"

  normal:
    black: "0x1a181a"
    red: "0xf85e84"
    green: "0x9ecd6f"
    yellow: "0xe5c463"
    blue: "0x7accd7"
    magenta: "0xab9df2"
    cyan: "0xef9062"
    white: "0xe3e1e4"

  bright:
    black: "0x1a181a"
    red: "0xf85e84"
    green: "0x9ecd6f"
    yellow: "0xe5c463"
    blue: "0x7accd7"
    magenta: "0xab9df2"
    cyan: "0xef9062"
    white: "0xe3e1e4"

font:
  normal:
    family: "MesloLGS NF"
    style: Regular 

  bold:
    family: "MesloLGS NF"
    style: Bold

  italic:
    family: "MesloLGS NF"
    style: Italic

background_opacity: 0.9
