import:
  # uncomment the flavour you want below:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml
env:
  TERM: xterm-256color 
window:
  padding:
    x: 3
    y: 3
  opacity: 0.9

font:
  size: 10
  normal:
    family: "JetBrains Mono"
    style: Regular 

