thamenato: ENC[AES256_GCM,data:K/6IjQJ+D3+YD6CR93ijOWP++EmDk3nkxJh0v9ikQmur6OW1Nl+54I6tb+a9AywGCtejVuIh9bTpIFxtjgit5h1fpj5W9eXNBg==,iv:2k2hCp4rA/QWXt4RJ1naMzt/QD7KeEq3sUK8PSFJcdM=,tag:bR0IWh1Oq25ZK0wqMifjWA==,type:str]
nmeusling: ENC[AES256_GCM,data:4VgQc39N5UjuBUZF3l4VGyY6RpA7JNf31CyrzxVDqQeUUtXJAWV3M+bv2UY0nN0laryrWZ02d/toqVVJfClUzWDzKk+bmOdx6w==,iv:h6GWXwEGUcaZFQeNU402ICsKXeo8fXSVB1XpkllFnbg=,tag:5HmpueB9fm1XDAeUhRqeiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15jkdns7a6m5j457ew0kr0lwznt5nje9fn76n7vy7c7u80k5ny5askks206
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTC9nWnppVGVock1ySCtt
            WG42RWZneCtORmVDaCtkV2hIQlpMVkt6aHg4ClUvbmIzV1dscmpFWmJNa1JFQzg4
            Sk9DR1paamU2bWpMZGlyYXYrTE1KRkEKLS0tIEM1Tno2VmV4ZEZiYW5nWHgxRVBM
            YXhGREpnL2QxL05WTk12UmxmM2VGQ3MKbJxokTlVj0QNzfFv58So0DLEdse3cCjv
            auwIXIEbkm3/w3W2z8ygB+VSiTwVdq9nakdhAzm8/dOxzmdF6RSyVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T21:56:19Z"
    mac: ENC[AES256_GCM,data:R8Jf8mukErJHjD0tGe0yqgi+Bek72RZm29/khnQUqyXA8nuwnGnk/cWarvvG5Kz6kfNXqZxguEMllruJhSi5vvv//NKlQOT3P22liCP06VdYoTryNENbhN/16ZaWT7r5na21KumfshxVSsg9njAwA/VHxbI8B5Dqoiz5Q3dDzQ4=,iv:WYlM9bwFC/IoNT+Z4CQVUl3rTCpbBf3PxvmTAfnZtZc=,tag:vHU98rphE6TBzEoWeLzcAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
